/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nakonieczny.jacek.rysowanie.view;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Jacek
 */
public class MainFrame extends javax.swing.JFrame {

    Graphics g = null;
    Color color = Color.CYAN;
    int arcWidth = 20;
    int arcHeight = 20;
    int l, r, t, b;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        g = jPanel1.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_rect = new javax.swing.JButton();
        btn_roundrect = new javax.swing.JButton();
        btn_oval = new javax.swing.JButton();
        btn_filloval = new javax.swing.JButton();
        btn_fillroundrect = new javax.swing.JButton();
        btn_fillrect = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_l = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_r = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_t = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_b = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn_rect1 = new javax.swing.JButton();
        btn_roundrect1 = new javax.swing.JButton();
        btn_oval1 = new javax.swing.JButton();
        btn_filloval1 = new javax.swing.JButton();
        btn_fillroundrect1 = new javax.swing.JButton();
        btn_fillrect1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_rect.setText("Prostokąt");
        btn_rect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rectActionPerformed(evt);
            }
        });

        btn_roundrect.setText("ZaokrProstokąt");
        btn_roundrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roundrectActionPerformed(evt);
            }
        });

        btn_oval.setText("Elipsa");
        btn_oval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ovalActionPerformed(evt);
            }
        });

        btn_filloval.setText("Elipsa");
        btn_filloval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fillovalActionPerformed(evt);
            }
        });

        btn_fillroundrect.setText("ZaokrProstokąt");
        btn_fillroundrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fillroundrectActionPerformed(evt);
            }
        });

        btn_fillrect.setText("Prostokąt");
        btn_fillrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fillrectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_rect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_roundrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_oval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_fillrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_fillroundrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_filloval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_rect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_roundrect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_oval)
                .addGap(18, 18, 18)
                .addComponent(btn_fillrect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_fillroundrect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_filloval)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("L");

        txt_l.setText("0");

        jLabel2.setText("P");

        txt_r.setText("0");

        jLabel3.setText("G");

        txt_t.setText("0");

        jLabel4.setText("D");

        txt_b.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(txt_l, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(txt_r, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 29, Short.MAX_VALUE)
                        .addComponent(txt_t, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_rect1.setText("Prostokąt");
        btn_rect1.setActionCommand("rect");
        btn_rect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rect1ActionPerformed(evt);
            }
        });

        btn_roundrect1.setText("ZaokrProstokąt");
        btn_roundrect1.setActionCommand("roundrect");
        btn_roundrect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rect1ActionPerformed(evt);
            }
        });

        btn_oval1.setText("Elipsa");
        btn_oval1.setActionCommand("oval");
        btn_oval1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rect1ActionPerformed(evt);
            }
        });

        btn_filloval1.setText("Elipsa");
        btn_filloval1.setActionCommand("foval");
        btn_filloval1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rect1ActionPerformed(evt);
            }
        });

        btn_fillroundrect1.setText("ZaokrProstokąt");
        btn_fillroundrect1.setActionCommand("froundrect");
        btn_fillroundrect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rect1ActionPerformed(evt);
            }
        });

        btn_fillrect1.setText("Prostokąt");
        btn_fillrect1.setActionCommand("frect");
        btn_fillrect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rect1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_rect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_roundrect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_oval1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_fillrect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_fillroundrect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_filloval1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_rect1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_roundrect1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_oval1)
                .addGap(18, 18, 18)
                .addComponent(btn_fillrect1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_fillroundrect1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_filloval1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_rectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rectActionPerformed
        l = Integer.parseInt(txt_l.getText());
        r = Integer.parseInt(txt_r.getText());
        t = Integer.parseInt(txt_t.getText());
        b = Integer.parseInt(txt_b.getText());
        g.setColor(Color.BLACK);
        g.clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        g.drawRect(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1);
    }//GEN-LAST:event_btn_rectActionPerformed

    private void btn_fillrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fillrectActionPerformed
        l = Integer.parseInt(txt_l.getText());
        r = Integer.parseInt(txt_r.getText());
        t = Integer.parseInt(txt_t.getText());
        b = Integer.parseInt(txt_b.getText());
        g.setColor(color);
        g.clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        g.fillRect(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1);
    }//GEN-LAST:event_btn_fillrectActionPerformed

    private void btn_roundrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roundrectActionPerformed
        l = Integer.parseInt(txt_l.getText());
        r = Integer.parseInt(txt_r.getText());
        t = Integer.parseInt(txt_t.getText());
        b = Integer.parseInt(txt_b.getText());
        g.setColor(Color.BLACK);
        g.clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        g.drawRoundRect(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1, arcWidth, arcHeight);
    }//GEN-LAST:event_btn_roundrectActionPerformed

    private void btn_ovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ovalActionPerformed
        l = Integer.parseInt(txt_l.getText());
        r = Integer.parseInt(txt_r.getText());
        t = Integer.parseInt(txt_t.getText());
        b = Integer.parseInt(txt_b.getText());
        g.setColor(Color.BLACK);
        g.clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        g.drawOval(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1);
    }//GEN-LAST:event_btn_ovalActionPerformed

    private void btn_fillroundrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fillroundrectActionPerformed
        l = Integer.parseInt(txt_l.getText());
        r = Integer.parseInt(txt_r.getText());
        t = Integer.parseInt(txt_t.getText());
        b = Integer.parseInt(txt_b.getText());
        g.setColor(color);
        g.clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        g.fillRoundRect(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1, arcWidth, arcHeight);
    }//GEN-LAST:event_btn_fillroundrectActionPerformed

    private void btn_fillovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fillovalActionPerformed
        l = Integer.parseInt(txt_l.getText());
        r = Integer.parseInt(txt_r.getText());
        t = Integer.parseInt(txt_t.getText());
        b = Integer.parseInt(txt_b.getText());
        g.setColor(color);
        g.clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        g.fillOval(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1);
    }//GEN-LAST:event_btn_fillovalActionPerformed

    private void btn_rect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rect1ActionPerformed
        l = Integer.parseInt(txt_l.getText());
        r = Integer.parseInt(txt_r.getText());
        t = Integer.parseInt(txt_t.getText());
        b = Integer.parseInt(txt_b.getText());
        g.clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        switch (evt.getActionCommand()) {
            case "rect":
                g.setColor(Color.BLACK);
                g.drawRect(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1);
                break;
            case "roundrect":
                g.setColor(Color.BLACK);
                g.drawRoundRect(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1, arcWidth, arcHeight);
                break;
            case "oval":
                g.setColor(Color.BLACK);
                g.drawOval(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1);
                break;
            case "frect":
                g.setColor(color);
                g.fillRect(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1);
                break;
            case "froundrect":
                g.setColor(color);
                g.fillRoundRect(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1, arcWidth, arcHeight);
                break;
            case "foval":
                g.setColor(color);
                g.fillOval(l, t, jPanel1.getWidth() - l - r - 1, jPanel1.getHeight() - t - b - 1);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btn_rect1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_filloval;
    private javax.swing.JButton btn_filloval1;
    private javax.swing.JButton btn_fillrect;
    private javax.swing.JButton btn_fillrect1;
    private javax.swing.JButton btn_fillroundrect;
    private javax.swing.JButton btn_fillroundrect1;
    private javax.swing.JButton btn_oval;
    private javax.swing.JButton btn_oval1;
    private javax.swing.JButton btn_rect;
    private javax.swing.JButton btn_rect1;
    private javax.swing.JButton btn_roundrect;
    private javax.swing.JButton btn_roundrect1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_b;
    private javax.swing.JTextField txt_l;
    private javax.swing.JTextField txt_r;
    private javax.swing.JTextField txt_t;
    // End of variables declaration//GEN-END:variables
}
