/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nakonieczny.jacek.semestr1.Kolokwium.gr1.Applet;

import java.util.*;
import javax.swing.*;
import nakonieczny.jacek.semestr1.Kolokwium.gr1.OsobaJN;
import nakonieczny.jacek.semestr1.Kolokwium.gr1.StudentJN;
import nakonieczny.jacek.semestr1.Kolokwium.gr1.StudentWyjatekJN;

/**
 *
 * @author Jacek
 */
public class StudentApplet extends javax.swing.JApplet {

    private ArrayList<OsobaJN> studenci;
    private int selectedIndex;

    /**
     * Initializes the applet StudentApplet
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    studenci = new ArrayList<>();
                    UpdateListJN();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_student = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_imie = new javax.swing.JTextField();
        txt_nazwisko = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_srednia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_dodaj = new javax.swing.JButton();
        btn_modyfikuj = new javax.swing.JButton();
        list_status = new javax.swing.JTextField();

        list_student.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        list_student.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                SelectionChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_student);

        jLabel1.setText("Imie");

        jLabel2.setText("Nazwisko");

        jLabel3.setText("Średnia");

        btn_dodaj.setText("Dodaj Studenta");
        btn_dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dodajActionPerformed(evt);
            }
        });

        btn_modyfikuj.setText("Modyfikuj Studenta");
        btn_modyfikuj.setEnabled(false);
        btn_modyfikuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modyfikujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_dodaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modyfikuj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_srednia, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txt_nazwisko)
                            .addComponent(txt_imie))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_imie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_srednia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_dodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_modyfikuj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        list_status.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(list_status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(list_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dodajActionPerformed
        // TODO add your handling code here:
        if (studenci.size() == 50) {
            JOptionPane.showMessageDialog(this, "Lista studenów osiągneła maksymalny rozmiar!", "UWAGA!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (WczytajStudentaJN() != null) {
            studenci.add(WczytajStudentaJN());
        }
        WyczyscPolaJN();
        UpdateListJN();
    }//GEN-LAST:event_btn_dodajActionPerformed

    private void UpdateListJN() {
        list_student.setListData(studenci.toArray());
        list_status.setText("Ilość studentów: " + studenci.size());
    }

    private void SelectionChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_SelectionChanged
        // TODO add your handling code here:
        btn_modyfikuj.setEnabled(true);
        selectedIndex = list_student.getSelectedIndex();
        if (selectedIndex > -1) {
            btn_dodaj.setEnabled(false);
            StudentJN s = (StudentJN) studenci.get(selectedIndex);
            txt_imie.setText(s.getImieJN());
            txt_nazwisko.setText(s.getNazwiskoJN());
            txt_srednia.setText(String.valueOf(s.getSredniaJN()));
        } else {
            btn_modyfikuj.setEnabled(false);
        }
    }//GEN-LAST:event_SelectionChanged

    private StudentJN WczytajStudentaJN() {
        StudentJN s = null;
        String imie = txt_imie.getText();
        String nazwisko = txt_nazwisko.getText();
        float srednia = 0;

        try {
            if ("".equals(imie)) {
                JOptionPane.showMessageDialog(this, "Nie podałeś imienia!", "UWAGA!", JOptionPane.WARNING_MESSAGE);
            }
            if ("".equals(nazwisko)) {
                JOptionPane.showMessageDialog(this, "Nie podałeś nazwiska!", "UWAGA!", JOptionPane.WARNING_MESSAGE);
                return null;
            }

            srednia = Float.parseFloat(txt_srednia.getText());

            s = new StudentJN(imie, nazwisko, srednia);
            return s;
        } catch (StudentWyjatekJN ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "UWAGA!", JOptionPane.WARNING_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Niepoprawna średnia!", "UWAGA!", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        return s;
    }
    private void btn_modyfikujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modyfikujActionPerformed
        // TODO add your handling code here:

        if (selectedIndex > -1) {
            if (WczytajStudentaJN() != null) {
                studenci.set(selectedIndex, WczytajStudentaJN());
            }
        }
        btn_dodaj.setEnabled(true);
        WyczyscPolaJN();
        UpdateListJN();
        btn_modyfikuj.setEnabled(false);
    }//GEN-LAST:event_btn_modyfikujActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dodaj;
    private javax.swing.JButton btn_modyfikuj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField list_status;
    private javax.swing.JList list_student;
    private javax.swing.JTextField txt_imie;
    private javax.swing.JTextField txt_nazwisko;
    private javax.swing.JTextField txt_srednia;
    // End of variables declaration//GEN-END:variables

    private void WyczyscPolaJN() {
        txt_imie.setText("");
        txt_nazwisko.setText("");
        txt_srednia.setText("");
    }

    public void main(String[] args) {
        StudentApplet applet = new StudentApplet();
        applet.setVisible(true);
    }
}
